#如果没有出现提示，那么可以使用CTRL+F9
#利用springboot的RelaxBinding可以使java类属性的小驼峰形式的变量名在application.yml中转化为中划线形式，小驼峰形式，下划线形式

acme:
  enabled: true
  remote-address: 192.168.0.108
  #  这里application.yml中的remote-address对应于AcmeProperties类属性中的    private InetAddress remoteAddress;
  #  驼峰命名到中划线命名是用到了@ConfigurationProperties("acme")的松散耦合
  security:
    username: liwenli
    password: liwenli
    roles:
      - liwenli
      - wangshuwei


  my-project:
    person:
      first-name: wenli
      last-name: li
