acme:
  enabled: true
  remote-address: 192.168.0.107
  security:
    username: liwenli
    password: liwenli
    roles:
      - liwenli
      - wangshuwei
spring:
  profiles: default

---
acme:
  enabled: true
  remote-address: 192.168.0.108
  security:
    username: liwenli
    password: liwenli
    roles:
      - liwenli
      - wangshuwei
spring:
  profiles: test

---
acme:
  enabled: true
  remote-address: 192.168.0.109
  security:
    username: liwenli
    password: liwenli
    roles:
      - liwenli
      - wangshuwei
spring:
  profiles: develop
---
acme:
  enabled: true
  remote-address: 192.168.0.110
  security:
    username: liwenli
    password: liwenli
    roles:
      - liwenli
      - wangshuwei
spring:
  profiles: product

