#如果没有出现提示，那么可以使用CTRL+F9 (目的是maven重新build项目，之后重新生成一个target目录)
person:
  age: 34
  email: liwenli@liwenli.com
  my-name: liwenli
  school:
    school-name: qqhredu

person2:
#  age: 34
  email: liwenli
  myName: liwenli
#  my-name: liwenli
  school:
    schoolName: qqhredu
